# Generated by Django 4.2.8 on 2023-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_allusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
