# Generated by Django 4.2.8 on 2023-12-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_is_denied'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRequestsFromcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('request_status', models.BooleanField(default=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_request', to='accounts.collegemodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_request', to='accounts.companymodel')),
            ],
        ),
    ]
